DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    ID VARCHAR(32) NOT NULL AUTO_INCREMENT  COMMENT '书籍ID;书籍ID' ,
    NAME VARCHAR(90)    COMMENT '书籍名称;书籍名称' ,
    PRICE DECIMAL(24,6)    COMMENT '价格;价格' ,
    AUTHOR VARCHAR(90)    COMMENT '作者;作者' ,
    SALES INT    COMMENT '销量;销量' ,
    STOCK INT    COMMENT '库存;库存' ,
    IMG_PATH VARCHAR(900)    COMMENT '封面图片URL;封面图片URL' ,
    PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 COMMENT = '书籍表';


CREATE UNIQUE INDEX PRIMARY ON BOOK();

DROP TABLE IF EXISTS ORDER;
CREATE TABLE ORDER(
    ORDER_ID VARCHAR(32) NOT NULL   COMMENT '订单号;订单号' ,
    CREATE_TIME DATETIME    COMMENT '创建时间;创建时间' ,
    PRICE DECIMAL(24,6)    COMMENT '订单总价;订单总价' ,
    STATUS VARCHAR(90)    COMMENT '订单状态;订单状态' ,
    USER_ID VARCHAR(32)    COMMENT '用户ID;用户ID' ,
    PRIMARY KEY (ORDER_ID)
)  COMMENT = '订单表';


CREATE UNIQUE INDEX PRIMARY ON ORDER();

DROP TABLE IF EXISTS ORDER_ITEM;
CREATE TABLE ORDER_ITEM(
    ID VARCHAR(32) NOT NULL AUTO_INCREMENT  COMMENT '订单项ID;订单项ID' ,
    NAME VARCHAR(90)    COMMENT '商品名称;书籍名称' ,
    COUNT INT    COMMENT '数量;数量' ,
    PRICE DECIMAL(24,6)    COMMENT '单价;单价' ,
    TOTAL_PRICE DECIMAL(24,6)    COMMENT '总价;总价' ,
    ORDER_ID VARCHAR(32)    COMMENT '订单号;订单号' ,
    PRIMARY KEY (ID)
)  COMMENT = '订单项表';


CREATE UNIQUE INDEX PRIMARY ON ORDER_ITEM();

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
    ID VARCHAR(32) NOT NULL AUTO_INCREMENT  COMMENT '用户ID;用户ID' ,
    ACCOUNT VARCHAR(90)    COMMENT '账号;账号' ,
    PASSWORD VARCHAR(90)    COMMENT '密码;密码' ,
    EMAIL VARCHAR(90)    COMMENT '邮箱;邮箱' ,
    PRIMARY KEY (ID)
)  COMMENT = '用户表';


CREATE UNIQUE INDEX PRIMARY ON USER();

